/**
 * AppBroadcast - Topic Registry for Pub/Sub Routing
 *
 * Hierarchical topic structure for event-driven architecture:
 * - APP.* - Application-level events
 * - ROUTE.* - Navigation events
 * - AUTH.* - Authentication events
 * - UI.* - User interface events
 */

const AppBroadcast = Object.freeze({
  // Application Events
  APP: 'APP',
  APP_READY: 'APP.READY',
  APP_ERROR: 'APP.ERROR',
  APP_SIGNOUT: 'APP.SIGNOUT',
  APP_AUTH: 'APP.AUTH',
  APP_USER_LOADED: 'APP.USER.LOADED',

  // Route Navigation Events
  ROUTE_NAV: 'ROUTE.NAV',
  ROUTE_NAV_BEFORE: 'ROUTE.NAV.BEFORE',
  ROUTE_NAV_AFTER: 'ROUTE.NAV.AFTER',
  ROUTE_NAV_ERROR: 'ROUTE.NAV.ERROR',

  // Authentication Events
  AUTH_SIGNIN: 'AUTH.SIGNIN',
  AUTH_SIGNIN_SUCCESS: 'AUTH.SIGNIN.SUCCESS',
  AUTH_SIGNIN_FAIL: 'AUTH.SIGNIN.FAIL',
  AUTH_SIGNUP: 'AUTH.SIGNUP',
  AUTH_SIGNUP_SUCCESS: 'AUTH.SIGNUP.SUCCESS',
  AUTH_SIGNUP_FAIL: 'AUTH.SIGNUP.FAIL',
  AUTH_VERIFY_LINK: 'AUTH.VERIFY.LINK',
  AUTH_SIGNOUT: 'AUTH.SIGNOUT',
  AUTH_SIGNOUT_SUCCESS: 'AUTH.SIGNOUT.SUCCESS',
  AUTH_FORGOT: 'AUTH.FORGOT',
  AUTH_FORGOT_SUCCESS: 'AUTH.FORGOT.SUCCESS',
  AUTH_RESETHASH: 'AUTH.RESETHASH',
  AUTH_RESETHASH_SUCCESS: 'AUTH.RESETHASH.SUCCESS',
  AUTH_RESETHASH_NAV: 'AUTH.RESETHASH.NAV',
  AUTH_TOKEN_EXPIRED: 'AUTH.TOKEN.EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH.TOKEN.INVALID',

  // UI Events
  UI_LOADING_START: 'UI.LOADING.START',
  UI_LOADING_END: 'UI.LOADING.END',
  UI_TOAST: 'UI.TOAST',
  UI_MODAL_OPEN: 'UI.MODAL.OPEN',
  UI_MODAL_CLOSE: 'UI.MODAL.CLOSE',

  // Web Component Events
  WC_APP_PRIMARY_NAV_LOGO: 'WC.APP.PRIMARY_NAV.LOGO',

  // Data Events
  DATA_REFRESH: 'DATA.REFRESH',
  DATA_UPDATE: 'DATA.UPDATE',
  DATA_ERROR: 'DATA.ERROR',
});

export default AppBroadcast;
